name: Continuous Integration Re-training

on:
  push:
    branches:
      - main

jobs:
  mlflow-run:
    runs-on: ubuntu-latest
    steps:
    - name: Unduh Source Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependensi
      run: |
        pip install mlflow tensorflow pandas numpy scikit-learn

    - name: Eksekusi Otomatis MLProject
      run: |
        mlflow run . --env-manager=local
