name: CI/CD MLflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow tensorflow scikit-learn

      - name: Run MLProject
        run: |
          mlflow run . --env-manager=local
          
          if [ -z "$PROJECT_FILE" ]; then
            echo "Error: File 'MLProject' TIDAK ditemukan di repositori!"
            echo "Daftar isi folder saat ini:"
            ls -R
            exit 1
          fi
          
          PROJECT_DIR=$(dirname "$PROJECT_FILE")
          echo "File ditemukan di: $PROJECT_FILE"
          echo "Menjalankan proyek dari folder: $PROJECT_DIR"
          
          # 2. Jalankan MLflow
          mlflow run "$PROJECT_DIR" --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          # Cari ID run terakhir di folder mlruns
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
      - name: Build Docker Model
        run: mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/smsml_ammar_fernanda_khoiri:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smsml_ammar_fernanda_khoiri:latest
